-- Recipe Management Database Schema
-- Run this script to create the database and populate it with sample data

CREATE DATABASE IF NOT EXISTS recipe_management;
USE recipe_management;

-- Create recipes table
CREATE TABLE recipes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    cuisine VARCHAR(100) NOT NULL,
    rating DECIMAL(2,1) DEFAULT NULL,
    prep_time INT DEFAULT NULL,
    cook_time INT DEFAULT NULL,
    total_time INT DEFAULT NULL,
    description TEXT,
    serves VARCHAR(50),
    calories VARCHAR(20),
    carbohydrate_content VARCHAR(20),
    cholesterol_content VARCHAR(20),
    fiber_content VARCHAR(20),
    protein_content VARCHAR(20),
    saturated_fat_content VARCHAR(20),
    sodium_content VARCHAR(20),
    sugar_content VARCHAR(20),
    fat_content VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_cuisine ON recipes(cuisine);
CREATE INDEX idx_rating ON recipes(rating);
CREATE INDEX idx_total_time ON recipes(total_time);
CREATE INDEX idx_title ON recipes(title);

-- Insert sample data
INSERT INTO recipes (
    title, cuisine, rating, prep_time, cook_time, total_time, description, serves,
    calories, carbohydrate_content, cholesterol_content, fiber_content, protein_content,
    saturated_fat_content, sodium_content, sugar_content, fat_content
) VALUES 
(
    'Sweet Potato Pie with Cinnamon Whipped Cream',
    'Southern Recipes',
    4.8,
    15,
    100,
    115,
    'Shared from a Southern recipe, this homemade sweet potato pie features a rich, creamy filling with warm spices and a flaky crust, topped with cinnamon whipped cream.',
    '8 servings',
    '389 kcal',
    '48 g',
    '78 mg',
    '3 g',
    '5 g',
    '10 g',
    '254 mg',
    '28 g',
    '21 g'
),
(
    'Classic Chicken Parmesan',
    'Italian',
    4.6,
    20,
    25,
    45,
    'Tender chicken breast coated in seasoned breadcrumbs, topped with marinara sauce and melted mozzarella cheese.',
    '4 servings',
    '520 kcal',
    '35 g',
    '125 mg',
    '2 g',
    '42 g',
    '8 g',
    '890 mg',
    '6 g',
    '24 g'
),
(
    'Beef Teriyaki Stir Fry',
    'Asian',
    4.4,
    10,
    15,
    25,
    'Quick and flavorful stir-fry with tender beef strips, fresh vegetables, and homemade teriyaki sauce.',
    '6 servings',
    '425 kcal',
    '28 g',
    '95 mg',
    '4 g',
    '35 g',
    '6 g',
    '1200 mg',
    '15 g',
    '18 g'
),
(
    'Spicy Chicken Tacos',
    'Mexican',
    4.7,
    25,
    20,
    45,
    'Authentic Mexican-style tacos with seasoned chicken, fresh salsa, and all your favorite toppings.',
    '4 servings',
    '340 kcal',
    '22 g',
    '85 mg',
    '5 g',
    '28 g',
    '4 g',
    '680 mg',
    '3 g',
    '16 g'
),
(
    'Mediterranean Salmon',
    'Mediterranean',
    4.9,
    15,
    18,
    33,
    'Herb-crusted salmon with Mediterranean flavors, served with roasted vegetables and lemon.',
    '4 servings',
    '380 kcal',
    '8 g',
    '110 mg',
    '3 g',
    '38 g',
    '5 g',
    '320 mg',
    '4 g',
    '22 g'
),
(
    'Chocolate Chip Cookies',
    'American',
    4.5,
    20,
    12,
    32,
    'Classic homemade chocolate chip cookies with a perfect chewy texture and plenty of chocolate chips.',
    '24 servings',
    '180 kcal',
    '24 g',
    '25 mg',
    '1 g',
    '2 g',
    '4 g',
    '95 mg',
    '16 g',
    '8 g'
),
(
    'Vegetable Curry',
    'Indian',
    4.3,
    15,
    30,
    45,
    'Rich and aromatic vegetable curry with coconut milk, spices, and fresh vegetables.',
    '6 servings',
    '280 kcal',
    '35 g',
    '0 mg',
    '8 g',
    '12 g',
    '15 g',
    '450 mg',
    '12 g',
    '18 g'
),
(
    'BBQ Pulled Pork',
    'American',
    4.6,
    20,
    480,
    500,
    'Slow-cooked pulled pork with tangy BBQ sauce, perfect for sandwiches or served with sides.',
    '8 servings',
    '420 kcal',
    '15 g',
    '110 mg',
    '1 g',
    '35 g',
    '8 g',
    '890 mg',
    '12 g',
    '22 g'
),
(
    'Greek Salad',
    'Mediterranean',
    4.2,
    15,
    0,
    15,
    'Fresh Mediterranean salad with tomatoes, cucumbers, olives, feta cheese, and olive oil dressing.',
    '4 servings',
    '220 kcal',
    '12 g',
    '35 mg',
    '4 g',
    '8 g',
    '6 g',
    '680 mg',
    '8 g',
    '18 g'
),
(
    'Beef Stroganoff',
    'Russian',
    4.4,
    20,
    25,
    45,
    'Creamy beef stroganoff with tender beef strips, mushrooms, and sour cream sauce over egg noodles.',
    '6 servings',
    '480 kcal',
    '32 g',
    '95 mg',
    '2 g',
    '28 g',
    '12 g',
    '750 mg',
    '4 g',
    '26 g'
),
(
    'Thai Green Curry',
    'Thai',
    4.7,
    25,
    20,
    45,
    'Authentic Thai green curry with coconut milk, vegetables, and aromatic herbs and spices.',
    '4 servings',
    '320 kcal',
    '18 g',
    '0 mg',
    '6 g',
    '15 g',
    '18 g',
    '890 mg',
    '10 g',
    '22 g'
),
(
    'Margherita Pizza',
    'Italian',
    4.5,
    30,
    15,
    45,
    'Classic Italian pizza with fresh mozzarella, tomatoes, basil, and olive oil on a crispy crust.',
    '4 servings',
    '350 kcal',
    '42 g',
    '45 mg',
    '3 g',
    '18 g',
    '8 g',
    '650 mg',
    '6 g',
    '14 g'
),
(
    'Fish and Chips',
    'British',
    4.1,
    20,
    15,
    35,
    'Traditional British fish and chips with beer-battered cod and crispy fries.',
    '4 servings',
    '580 kcal',
    '45 g',
    '85 mg',
    '4 g',
    '32 g',
    '6 g',
    '890 mg',
    '3 g',
    '28 g'
),
(
    'Chicken Tikka Masala',
    'Indian',
    4.8,
    30,
    25,
    55,
    'Creamy and flavorful chicken tikka masala with tender chicken in a rich tomato-based sauce.',
    '6 servings',
    '420 kcal',
    '18 g',
    '95 mg',
    '3 g',
    '35 g',
    '12 g',
    '780 mg',
    '12 g',
    '24 g'
),
(
    'Caesar Salad',
    'American',
    4.0,
    15,
    0,
    15,
    'Classic Caesar salad with romaine lettuce, parmesan cheese, croutons, and Caesar dressing.',
    '4 servings',
    '280 kcal',
    '12 g',
    '45 mg',
    '3 g',
    '8 g',
    '6 g',
    '590 mg',
    '3 g',
    '24 g'
),
(
    'Pad Thai',
    'Thai',
    4.6,
    20,
    10,
    30,
    'Traditional Thai stir-fried noodles with shrimp, tofu, bean sprouts, and tamarind sauce.',
    '4 servings',
    '380 kcal',
    '52 g',
    '125 mg',
    '3 g',
    '18 g',
    '3 g',
    '1200 mg',
    '18 g',
    '12 g'
),
(
    'Mushroom Risotto',
    'Italian',
    4.4,
    15,
    30,
    45,
    'Creamy Italian risotto with mixed mushrooms, parmesan cheese, and white wine.',
    '4 servings',
    '420 kcal',
    '58 g',
    '35 mg',
    '2 g',
    '12 g',
    '8 g',
    '680 mg',
    '4 g',
    '16 g'
),
(
    'Korean Bulgogi',
    'Korean',
    4.7,
    120,
    15,
    135,
    'Marinated Korean beef bulgogi with sweet and savory flavors, served with rice.',
    '4 servings',
    '380 kcal',
    '15 g',
    '85 mg',
    '1 g',
    '32 g',
    '6 g',
    '890 mg',
    '12 g',
    '18 g'
),
(
    'French Onion Soup',
    'French',
    4.3,
    20,
    45,
    65,
    'Classic French onion soup with caramelized onions, beef broth, and melted Gruyère cheese.',
    '4 servings',
    '320 kcal',
    '28 g',
    '45 mg',
    '3 g',
    '15 g',
    '12 g',
    '1200 mg',
    '18 g',
    '18 g'
),
(
    'Chicken Fajitas',
    'Mexican',
    4.5,
    20,
    15,
    35,
    'Sizzling chicken fajitas with bell peppers, onions, and warm tortillas with all the fixings.',
    '4 servings',
    '350 kcal',
    '28 g',
    '85 mg',
    '4 g',
    '28 g',
    '4 g',
    '720 mg',
    '6 g',
    '14 g'
);
